version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ./db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${MAIN_DB}
      POSTGRES_USER: ${MAIN_USER}
      POSTGRES_PASSWORD: ${MAIN_PASSWORD}
      POSTGRES_HOST: ${MAIN_HOST}
      POSTGRES_PORT: ${MAIN_PORT}

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A mysite worker -l INFO
    volumes:
      - ./:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command: celery -A mysite beat -l INFO
    volumes:
      - ./:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis

  redis:
      image: redis:latest

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

  flower:
    build: .
    image: mher/flower:latest
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker

  flask:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./:/code
    ports:
      - "5000:5000"
    env_file:
      - .env
