# Generated by Django 4.1.1 on 2023-01-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='vehicle_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
